"""
Property-based tests for Loki client module.

These tests verify universal properties that should hold across all inputs
using Hypothesis for property-based testing.
"""

import pytest
import requests
from unittest.mock import Mock, patch, MagicMock
from hypothesis import given, strategies as st, settings
from backend.loki_client import get_labels, query_logs, push_log, LokiClientError
from backend.config import config


# Feature: log-query-system, Property 2: Backend queries Loki for labels
# Validates: Requirements 1.2
@settings(max_examples=100)
@given(
    status_code=st.integers(min_value=200, max_value=299),
    labels=st.lists(st.text(min_size=1, max_size=20), min_size=0, max_size=10)
)
@patch('backend.loki_client.requests.get')
def test_property_get_labels_queries_loki_endpoint(mock_get, status_code, labels):
    """
    Property 2: Backend queries Loki for labels
    
    For any label request received by the backend, the backend should make 
    an API call to Loki's api/v1/label endpoint.
    """
    # Setup mock response
    mock_response = Mock()
    mock_response.status_code = status_code
    mock_response.json.return_value = {'data': labels}
    mock_response.raise_for_status = Mock()
    mock_get.return_value = mock_response
    
    # Execute
    result = get_labels()
    
    # Verify: Backend should query the correct Loki endpoint
    expected_url = config.get_loki_labels_url()
    mock_get.assert_called_once()
    
    # Check that the URL called matches the expected Loki labels endpoint
    actual_url = mock_get.call_args[0][0]
    assert actual_url == expected_url, \
        f"Backend should query Loki at {expected_url}, but queried {actual_url}"
    
    # Verify result matches what Loki returned
    assert result == labels


# Feature: log-query-system, Property 8: Backend forwards queries to Loki
# Validates: Requirements 3.4
@settings(max_examples=100)
@given(
    label_key=st.text(min_size=1, max_size=20, alphabet=st.characters(min_codepoint=97, max_codepoint=122)),
    label_value=st.text(min_size=1, max_size=20, alphabet=st.characters(min_codepoint=97, max_codepoint=122)),
    start_time=st.one_of(st.none(), st.text(min_size=1, max_size=30)),
    end_time=st.one_of(st.none(), st.text(min_size=1, max_size=30))
)
@patch('backend.loki_client.requests.get')
def test_property_query_logs_forwards_to_loki(mock_get, label_key, label_value, start_time, end_time):
    """
    Property 8: Backend forwards queries to Loki
    
    For any valid log query received by the backend, the backend should send 
    a request to Loki at api/v1/loki/logs with all provided parameters 
    (label, start_time, end_time).
    """
    # Setup mock response
    mock_response = Mock()
    mock_response.status_code = 200
    mock_response.json.return_value = {
        'data': {
            'result': []
        }
    }
    mock_response.raise_for_status = Mock()
    mock_get.return_value = mock_response
    
    # Construct label in format "key:value"
    label = f"{label_key}:{label_value}"
    
    # Execute
    result = query_logs(label=label, start_time=start_time, end_time=end_time)
    
    # Verify: Backend should query the correct Loki endpoint
    expected_url = config.get_loki_query_url()
    mock_get.assert_called_once()
    
    # Check that the URL called matches the expected Loki query endpoint
    actual_url = mock_get.call_args[0][0]
    assert actual_url == expected_url, \
        f"Backend should query Loki at {expected_url}, but queried {actual_url}"
    
    # Verify all parameters are forwarded
    call_kwargs = mock_get.call_args[1]
    params = call_kwargs.get('params', {})
    
    # Label should be converted to LogQL format and included
    assert 'query' in params, "Query parameter should be included"
    
    # Start time should be forwarded if provided
    if start_time is not None:
        assert 'start' in params, "Start time should be forwarded when provided"
        assert params['start'] == start_time
    
    # End time should be forwarded if provided
    if end_time is not None:
        assert 'end' in params, "End time should be forwarded when provided"
        assert params['end'] == end_time


# Feature: log-query-system, Property 11: Logs pushed to correct endpoint
# Validates: Requirements 4.2
@settings(max_examples=100)
@given(
    message=st.text(min_size=1, max_size=200),
    level=st.sampled_from(['DEBUG', 'INFO', 'WARNING', 'ERROR']),
    has_custom_labels=st.booleans()
)
@patch('backend.loki_client.requests.post')
def test_property_push_log_uses_correct_endpoint(mock_post, message, level, has_custom_labels):
    """
    Property 11: Logs pushed to correct endpoint
    
    For any log entry generated by the backend, the log should be pushed 
    to Loki at http://localhost:3100/loki/api/v1/push.
    """
    # Setup mock response
    mock_response = Mock()
    mock_response.status_code = 204
    mock_response.raise_for_status = Mock()
    mock_post.return_value = mock_response
    
    # Prepare labels
    labels = {'custom': 'label'} if has_custom_labels else None
    
    # Execute
    result = push_log(message=message, level=level, labels=labels)
    
    # Verify: Backend should push to the correct Loki endpoint
    expected_url = config.get_loki_push_url()
    mock_post.assert_called_once()
    
    # Check that the URL called matches the expected Loki push endpoint
    actual_url = mock_post.call_args[0][0]
    assert actual_url == expected_url, \
        f"Backend should push logs to {expected_url}, but pushed to {actual_url}"
    
    # Verify the push was successful
    assert result is True
    
    # Verify the payload structure is correct
    call_kwargs = mock_post.call_args[1]
    payload = call_kwargs.get('json', {})
    
    assert 'streams' in payload, "Payload should contain streams"
    assert len(payload['streams']) > 0, "Streams should not be empty"
    
    # Verify labels are included
    stream = payload['streams'][0]
    assert 'stream' in stream, "Stream should contain labels"
    assert 'values' in stream, "Stream should contain values"
